# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               n8dgr8
tagline:             'Some Rants'
description:         ''
url:                 http://n8dgr8.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Nathan S
  url:               https://twitter.com/the_real_n8dgr8
  email:             nschlehlein@pillartechnology.com

# Custom vars
version:             1.0.0
