# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               n8dgr8
tagline:             'Unpopular Mechanic'
description:         ''
url:                 http://n8dgr8.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              n8dgr8
  url:               https://twitter.com/the_real_n8dgr8
  email:             nschlehlein@pillartechnology.com

# Custom vars
version:             Mk.82
